name: Load image files to s3 and image data to ImagesCollection

# on: 
#   schedule: 
#     - cron: 0 22 */5 * *

on:
  push:
    branches:
      - main

jobs: 
  run-script:
    runs-on: ubuntu-latest
  
    steps: 
      - name: Checkout repository 
        uses: actions/checkout@v2

      - name: Setup node.js
        uses: actions/setup-node@v1
        with: 
          node-version: 12.x

      - name: Install dependencies
        run: npm install 

      - name: Run script
        run: node utils/scripts/imageProcessing.js

      - name: Get GitHub Email
        id: get_email
        run: |
          GITHUB_ACTOR_EMAIL=$(curl -s -H "Authorization: Bearer $GITHUB_TOKEN" \
          https://api.github.com/users/$GITHUB_ACTOR/emails | \
          jq -r '.[0].email')
          echo "GITHUB_ACTOR_EMAIL=$GITHUB_ACTOR_EMAIL" >> $GITHUB_ENV

      - name: Commit and push changes 
        run: |
          git config --local user.email "$GITHUB_ACTOR_EMAIL"
          git config --local user.name "${{ github.actor }}"
          git add .
          git commit -m "Auto-commit after image processing"
          git push 