name: Load image files to s3 and image data to ImagesCollection

# on: 
#   schedule: 
#     - cron: 0 22 */5 * *

on:
  push:
    branches:
      - main

jobs: 
  run-script:
    runs-on: ubuntu-latest
  
    steps: 
      - name: Checkout repository 
        uses: actions/checkout@v2

      - name: Setup node.js
        uses: actions/setup-node@v1
        with: 
          node-version: 12.x

      - name: Install dependencies
        run: npm install 

      - name: Run script
        run: node utils/scripts/imageProcessing.js

      - name: Install jq
        run: sudo apt-get install jq

      - name: Get GitHub Email
        id: get_email
        run: |
          GITHUB_ACTOR_EMAIL=$(curl -L \
          -H "Accept: application/vnd.github+json" \
          -H "Authorization: Bearer $GITHUB_TOKEN" \
          -H "X-GitHub-Api-Version: 2022-11-28" \
          https://api.github.com/user/emails |
          jq -r '.email')
          echo "GitHub API Response: $RESPONSE"
          GITHUB_ACTOR_EMAIL=$(echo "$RESPONSE" | jq -r '.email')
          echo "Fetched github email: $GITHUB_ACTOR_EMAIL"
          echo "GITHUB_ACTOR_EMAIL=$GITHUB_ACTOR_EMAIL" >> $GITHUB_ENV

      - name: Commit and push changes 
        run: |
          git config --local user.email "$GITHUB_ACTOR_EMAIL"
          git config --local user.name "${{ github.actor }}"
          git add .
          git commit -m "Auto-commit after image processing"
          git push 